### ISSUE TITLE
Error: Could not find a version that satisfied the version range

### ISSUE THREAD

**Issue by XBeg9** [pulumi/setup-pulumi#23]
I needed to set the latest 3.7.0 version

```
Run pulumi/setup-pulumi@v2
  with:
    pulumi-version: 3.7.0
Configured range: 3.7.0

Error: Could not find a version that satisfied the version range
```

**Comment by XBeg9** [comment]
tried with latest
```
Configured range: latest
Matched version: v3.6.1
```

**Comment by stack72** [comment]
Hi @XBeg9 

I apologise for this error - this is due to https://github.com/pulumi/docs/pull/6233 not being merged earlier - I have just merged and all should be better now

Paul
